deploy:
  provider: heroku
  api_key:
    secure: FC6bWcFDVl1elO9GLck4tRddI6frULAKk+aqiZqDcNzG6lF6JIGaqYIElrh6rPXo4TdRUTYvfP1rC97NbFmaKdzHelVWE5DherNRa5drLf6/L8YlxKSCKZ+GJjcCoh3X5BsEDbNMsQQr2/cLgnswBVreiZuaOIW9EkcabqGQkHy8dui6VBGREA8NfH4hRoGNbrzbVmDutrQgWnQ2BLabXmcunY3EePYwfG9zfxBP7gvxnk9EJoR0nKo40HjnOlApvc1lm/eNINvbdB31+TO6DOe/FqOBWn1ibe4KvpYD53l2bS9b1h83GvdBvivcUvdmzJYmW39ahJBMeH2oJgpQtuMtgSwRjo55/HkUWpslFKRNU/VJtRJmI3heAf7Vbn2/c2296I/Y/KsCoP42/Fd4P3mB5gq4robyrzwlsPUsetmGbZanDPJaEIHdzBxiGET5NTOY+I86KxHoBOvwXE/Jckp/aQUCITZb56zpHO/na15IS0jsIicGfQ/B6hb6joPQQzDFo8/NCKEVzGeq1KHTrwupcDK//f41v1Pu7hv7X9zNoNGfBck8RU4+pDAJWgsGUVoM5s/MSYdCzPjENASMp65kxKc74WJHGSfMFFhPA6NPc80QK6xaLMmRlVIxOAoz5BmgTev7Hll81Mx/3HKpHNt2Bxzre3x8aqIv9WD9OD8=
  app: main-app
  on:
    repo: Practice-Hacker/main-app
  skip_cleanup: 'true'
