deploy:
  provider: heroku
  api_key:
    secure: DAo0LLHdxK+L/M35fMnC/gdlk8Tr3b7gNCe6VfTRfnN1qVGW07nMztvXw2Sn2imnnbaDOHHjMqfe3/OlVKE4M89SWZvmgXCeD4TRSl4Sdgs4b7DJDaL+EqLFF0PLF70WbljVfIP1YIkw3a4VDKyJC3IyN1PrCHfFfqx3hAeBYuofqOh/2kLErb15SU0aDtYPaPYoTGac5tov9jlpmsnbVF2/fHimozVvUVQSpFOmoWBbH26Pt7v5oaQqsumFPIA7GAW/VvgTB/ocoBNRjp+nD/rskZi2kRH7iLGk3IFVm+26AZx3pIE2cVQuS+Po63XjpSB3teC+JeDobKH1Al2BFGl30/woL5CaNTr8LAUnp9cdmDLemJ2TkGvqjPfh/XjvrxTmKpg1G4Q+2+cVy1rXb1zJj799TEuTk8w9z58Qz3ZmnQxjQ7tjr6nOydGGQ7SU18vIZ4rAdAJ/dcYqCBhhnCchpvQMqr1QSD3XTvMy8dHcXDxTKn9oZQUjiIOsN3noH3NY10oRTs0SHkG+9II3iSMTlZ6KJA/OIb/zA1K7pIDnV2KjGu096uhhX47PD1NhFIee+dDdbaLs623vWZO3lVKCau5KnI8EJYLyHDnb5R0pRr+EPRYkGgKBNIy5Qulo2HxGkQ8EFozGuMRdNI2ACK9ihU6q/gMNR3Dp1jRrvK0=
  app: practice-hacker-main-app
  on:
    repo: Practice-Hacker/main-app
  skip_cleanup: 'true'
