language: ruby
cache: bundler
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_script:
- psql -c 'create database main_app_test;' -U postgres
script:
- bundle exec rails db:{drop,create,migrate,seed} RAILS_ENV=test
- bundle exec rspec
running: rspec
